# Generated by Django 4.2.26 on 2025-12-09 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('published_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('hepburn', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('release', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='categories.categories')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'books',
            },
        ),
    ]
